[package]
name = "oops"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
regex = "1.10"
walkdir = "2.4"
notify = "6.1"
colored = "3.0.0"
chrono = "0.4.41"
rand = "0.9"
